- name: Install PostgreSQL dependencies
  action: apt pkg={{item}} state=latest
  with_items:
    - python-pycurl
    - python-psycopg2

- name: Add PostgreSQL repo key
  apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc

- name: Add PostgreSQL repo
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main'

- name: Install PostgreSQL
  apt: pkg=postgresql-9.4 state=latest update_cache=true

- name: Restart PostgreSQL
  command: service postgresql restart

- name: Copy valid pg_hba.conf
  template: src=pg_hba.conf.j2 dest=/etc/postgresql/9.4/main/pg_hba.conf
  notify:
  - postgresql restart

- name: Copy valid postgresql.conf
  template: src=postgresql.conf.j2 dest=/etc/postgresql/9.4/main/postgresql.conf
  notify:
  - postgresql restart

- name: Create deploy user db
  sudo_user: postgres
  postgresql_db: 'name={{ deploy_user }}'

- name: Create deploy_user superuser
  sudo_user: postgres
  postgresql_user: 'name={{ deploy_user }} password=NULL role_attr_flags=SUPERUSER'

- name: Create app db
  sudo_user: postgres
  postgresql_db: 'name={{ pg.db }}'

- name: Create app db user
  sudo_user: postgres
  postgresql_user: 'name={{ pg.user }} password={{ pg.pass }}'

- name: Grant all privs on app db to app db user
  sudo_user: postgres
  postgresql_privs: >
    db=postgres
    privs=ALL
    type=database
    obj={{ pg.db }}
    role={{ pg.user }}
